#!/bin/bash
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# skip their stupid [ -f `which java` ] test, which will always fail on Gentoo
export APP_SKIP_J2SE_TEST=1
export GENTOO_VM=$( eval $(gjl --get-vm -p datamodeler) && echo ${gjl_vm} )
export JAVA_HOME=$(java-config -o)

cd /opt/datamodeler/datamodeler/bin && exec bash datamodeler $@
